name: EBikeCesena

services:
  ride-service:
    image: ride-service
    depends_on:
      - api-gateway
    networks:
      - ebike-network
    ports:
      - "8080:8080"
    expose:
      - 8080
  user-service:
    image: user-service
    depends_on:
      - api-gateway
    networks:
      - ebike-network
    ports:
      - "8081:8081"
    expose: 
      - 8081
  bike-service:
    image: bike-service
    depends_on:
      - api-gateway
    networks:
      - ebike-network
    ports:
      - "8082:8082"
    expose:
      - 8082
  api-gateway:
    image: api-gateway
    networks:
      - ebike-network
    ports:
      - "5701:5701"
      - "8085:8085"
    expose: 
      - 8085
  configuration-server:
    image: configuration-server
    depends_on:
      - api-gateway
    networks:
      - ebike-network
    ports:
      - "8090:8090"
    expose:
      - 8090
    volumes:
      - C:/UNI/Configurations:/Configurations
networks:
  ebike-network:
    driver: bridge
volumes:
  form: